/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ad_2022_23_practica_01_explorador_lorenzo_bautista;

import java.io.File;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Loren Baucas
 */
public class Explorador extends javax.swing.JFrame {
    
    String tipoExtension;

    /**
     * Creates new form Explorador
     */
    public Explorador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lDir = new javax.swing.JLabel();
        lExt = new javax.swing.JLabel();
        tDir = new javax.swing.JTextField();
        tExt = new javax.swing.JTextField();
        jScrollPane = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        bLupa1 = new javax.swing.JButton();
        bLupa2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Explorador de archivos");

        lDir.setText("Indique directorio:");

        lExt.setText("Indique extension:");

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Extension", "Tamaño", "Fichero/Directorio"
            }
        ));
        jTable.setAlignmentX(0.1F);
        jScrollPane.setViewportView(jTable);

        bLupa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ad_2022_23_practica_01_explorador_lorenzo_bautista/lupa.jpg"))); // NOI18N
        bLupa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLupa1ActionPerformed(evt);
            }
        });

        bLupa2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ad_2022_23_practica_01_explorador_lorenzo_bautista/lupa.jpg"))); // NOI18N
        bLupa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLupa2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lExt)
                            .addComponent(lDir))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tExt)
                            .addComponent(tDir, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bLupa1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bLupa2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lDir)
                            .addComponent(tDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(bLupa1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lExt)
                            .addComponent(tExt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(bLupa2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(55, 55, 55)
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bLupa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLupa1ActionPerformed
        //Pongo las filas a 0
        DefaultTableModel ficheros = (DefaultTableModel) jTable.getModel();
        ficheros.setRowCount(0);
        
        //Si no ha puesto ninguna ruta saldra un error
        if(tDir.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "No has especificado ninguna ruta", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        //Guardo la ruta
        String s = null;
        s = tDir.getText();
        
        //Si la ruta existe procedera a realizar la lectura de datos y a mostrarlos posteriormente, sino saldra un error de que no existe
        if (!s.isEmpty()) {
            File fichero = new File(s); 
            if (fichero.exists()) {

                //Creo el array y meto los datos
                File[] listaFicheros = fichero.listFiles();
                ArrayList<DatosArray> d = new ArrayList<DatosArray>();

                for (int i = 0; i < listaFicheros.length; i++) {
                    String nombre = listaFicheros[i].getName();
                    
                    //Si tiene extension la mostrara
                    String extension = null;
                    for (int e = 0; e < nombre.length(); e++) {
                        if (nombre.charAt(e) == '.') {
                            extension = nombre.substring(e, nombre.length());
                        }
                    }
                    DatosArray datos = new DatosArray(nombre, extension, listaFicheros[i].length(), listaFicheros[i].isFile());
                    d.add(datos);
                }

                //Mete los datos del array en el jTable
                for (int i = 0; i < d.size(); i++) {
                    ficheros.addRow(new Object[]{null, null, null, null});

                    DatosArray anadirDato = (DatosArray) d.get(i);

                    jTable.setValueAt(anadirDato.getNombre(), i, 0);
                    jTable.setValueAt(anadirDato.getExtension(), i, 1);
                    jTable.setValueAt(anadirDato.getTamaño(), i, 2);
                    jTable.setValueAt(anadirDato.getArchivoDirectorio(), i, 3);

                }
            }else{
                //Si la ruta no existe mostrara un mensaje de error
                JOptionPane.showMessageDialog(this, "La ruta especificada no existe", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_bLupa1ActionPerformed

    private void bLupa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLupa2ActionPerformed
        //Se realizan las acciones del primer boton
        bLupa1.doClick();
        
        DefaultTableModel n = (DefaultTableModel) jTable.getModel();
        int nFilas = n.getRowCount();
        
        //Filtro las extensiones y despues quito las filas de los ficheros que no tengan la extension especificada
        if (tipoExtension!=null){
        if (!tipoExtension.equals("1")) {
            tExt.setText(tipoExtension);
        }}
        String ext = tExt.getText();

        for (int i = nFilas - 1; i > -1; i--) {
            String extensiones = (String) n.getValueAt(i, 1);
            if (extensiones == null) {
                extensiones = "";
            }
            //Si no tienen esa extension se quitan del jTable
            if (!extensiones.equalsIgnoreCase(ext)) {
                n.removeRow(i);
            }
        }
    }//GEN-LAST:event_bLupa2ActionPerformed
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Explorador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Explorador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Explorador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Explorador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Explorador().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bLupa1;
    private javax.swing.JButton bLupa2;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTable jTable;
    private javax.swing.JLabel lDir;
    private javax.swing.JLabel lExt;
    private javax.swing.JTextField tDir;
    private javax.swing.JTextField tExt;
    // End of variables declaration//GEN-END:variables
}
